### ISSUE TITLE
Script Request

### ISSUE THREAD

**Issue by matheusbach** [nulastudio/HostFXRPatcher#3]
Can you provide the build script you use so we can patch and build our own .dlls? this makes it easier for the case of missing dll for the latest version and to check the integrity of the files. Thanks in advance

**Comment by liesauer** [comment]
hey, @matheusbach, i am really sorry that i didn't response in time! the build scripts is under the [`Patcher` branch](https://github.com/nulastudio/HostFXRPatcher/tree/Patcher) and i have updated the scripts to make it easy to used and building the missing dlls  these days. you can build your own dlls by following [the workflow](https://github.com/nulastudio/HostFXRPatcher/tree/Patcher#readme) now. thanks for trying NetCoreBeauty and HostFXRPatcher!
