### ISSUE TITLE
Error when using patched libhostfxr.so on linux/arm64

### ISSUE THREAD

**Issue by tomazv** [nulastudio/HostFXRPatcher#4]
I'm getting this error when using patched libhostfxr.so on linux-arm64 (v6.0.2):

```
Failed to load /app/libhostfxr.so, error: /app/libhostfxr.so: cannot open shared object file: No such file or directory
The library libhostfxr.so was found, but loading it from /app/libhostfxr.so failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063370
```

This happens on a simple hello world console app. If I use default libhostfxr.so, it works fine. It also works fine on other platforms (linux-x64, win-x64).

Is there anything I can do to make it work?

**Comment by liesauer** [comment]
are you using `NetCoreBeauty` or just the patched libhostfxr.so for other reasons?

**Comment by tomazv** [comment]
I am using just patched libhostfxr.so. The main reason is that I have multiple executables with shared libraries. Some of those libraries have same name but different versions for each executable. We put each library in their own folder which includes version number. So we patch deps.json file ourselves but use libhostfxr.so in order for relative paths from additionalProbingPaths to work.

I have, however just tried HelloWorld with NetCoreBeauty on linux-arm64 and I'm getting the same error. It works fine for linux-x64.

I am using docker with ubuntu base image to test this.

**Comment by liesauer** [comment]
try using `ldd` or set `COREHOST_TRACE=1` to check the missing dependencies.

**Comment by tomazv** [comment]
Using `COREHOST_TRACE=1` returns this:

```
--- Invoked apphost [version: 6.0.2, commit hash: 839cdfb0ecca5e0be3dbccd926e7651ef50fdf10] main = {
./ConsoleApp17
}
The managed DLL bound to this executable is: 'ConsoleApp17.dll'
Resolved fxr [/app/libhostfxr.so]...
Failed to load /app/libhostfxr.so, error: /app/libhostfxr.so: cannot open shared object file: No such file or directory
The library libhostfxr.so was found, but loading it from /app/libhostfxr.so failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063370
```

Running `ldd libhostfxr.so` returns this:

```
        not a dynamic executable
```

Running `ldd libhostfxr.so.bak` returns this:

```
        libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x00000055018a8000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000005501a8f000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000005501b39000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000005501b5d000)
        /lib/ld-linux-aarch64.so.1 (0x0000005500000000)
```

Unpatched version works fine - I just rename libhostfxr.so.bak to libhostfxr.so and copy all libraries to root and run it.

**Comment by liesauer** [comment]
look likes the artifact does not cross build correctly. it is a `x64` build. i will try rebuilding those artifacts later.
```
ubuntu@ubuntu:~/publish$ readelf -d libhostfxr.so.bak | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-aarch64.so.1]
ubuntu@ubuntu:~/publish$ readelf -d libhostfxr.so | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
```

**Comment by liesauer** [comment]
all broken artifacts have been reuploaded.

**Comment by tomazv** [comment]
Thanks!

I have tried version 6.0.3 and it works without problems.
